development:
  adapter: mysql2
  database: project
  pool: 5
  timeout: 5000
  username: root
  password:
test:
  adapter: mysql2
  database: project_testing
  pool: 5
  timeout: 5000
  username: root
  password:
production:
  adapter: mysql2
  database: project_production
  pool: 5
  timeout: 5000
  username: root
  password:
