development:
  adapter: mysql2
  database: project
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  database: project_testing
  pool: 5
  timeout: 5000
production:
  adapter: mysql2
  database: project_production
  pool: 5
  timeout: 5000
